export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const EMAIL_RESET_SUCCESS = "EMAIL_RESET_SUCCESS";
export const EMAIL_RESET_ERROR = "EMAIL_RESET_ERROR";
